#!/bin/bash
echo "Варіант #3: Читання файлу з нульовими правами"
test_file="zero_access.txt"
echo "Секретний вміст" > "$test_file"
chmod 000 "$test_file"
echo "Спроба читання звичайним користувачем:"
cat "$test_file"
echo "Результат: $?"
echo "Спроба читання через sudo:"
sudo cat "$test_file"
echo "Результат: $?"
chmod 644 "$test_file"
rm -f "$test_file"
echo "Висновок: Звичайний користувач не може читати файл з правами 000, але root може."
